kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo
        name: mongo

---
kind: Service
apiVersion: v1
metadata:
   name: mongo
spec:
   type: ClusterIP
   ports:
    - port: 27017
   selector:
     app: mongodb

---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: myapp
  name: my-mongo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: devopsedu/employee
        name: my-mongo-app

---
kind: Service
apiVersion: v1
metadata:
  name: my-mongo-app-svc
spec:
  type: NodePort
  ports:
   - port: 8888
  selector:
    app: myapp